[package]
name = "macros"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["bitfl0wer"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
syn = { version = "2.0.74", features = ["full"] }
